//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATURALAR
    {
        public int ID { get; set; }
        public string FATURANO { get; set; }
        public Nullable<int> TARIHID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<int> FATURAID { get; set; }
    
        public virtual FATURA FATURA { get; set; }
        public virtual SEPET SEPET { get; set; }
        public virtual SEPETSATIR SEPETSATIR { get; set; }
    }
}
