//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIS()
        {
            this.FATURA = new HashSet<FATURA>();
        }
    
        public int ID { get; set; }
        public string FISNO { get; set; }
        public Nullable<int> SEPETID { get; set; }
        public Nullable<int> PERSONELID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURA> FATURA { get; set; }
        public virtual PERSONELLER PERSONELLER { get; set; }
        public virtual SEPET SEPET { get; set; }
    }
}
