//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIYATDEGISTIR
    {
        public int ID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<System.DateTime> DTARIH { get; set; }
        public Nullable<double> EFIYAT { get; set; }
    
        public virtual URUNLER URUNLER { get; set; }
    }
}
