//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REEDER2Entities : DbContext
    {
        public REEDER2Entities()
            : base("name=REEDER2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTMANLAR> DEPARTMANLAR { get; set; }
        public virtual DbSet<FATURA> FATURA { get; set; }
        public virtual DbSet<FATURALAR> FATURALAR { get; set; }
        public virtual DbSet<FIS> FIS { get; set; }
        public virtual DbSet<KATEGORILER> KATEGORILER { get; set; }
        public virtual DbSet<MUSTERI> MUSTERI { get; set; }
        public virtual DbSet<PERSONELLER> PERSONELLER { get; set; }
        public virtual DbSet<SEHIRLER> SEHIRLER { get; set; }
        public virtual DbSet<SEPET> SEPET { get; set; }
        public virtual DbSet<SEPETSATIR> SEPETSATIR { get; set; }
        public virtual DbSet<URUNLER> URUNLER { get; set; }
        public virtual DbSet<SAYAC> SAYAC { get; set; }
        public virtual DbSet<FIYATDEGISTIR> FIYATDEGISTIR { get; set; }
    }
}
