//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUSTERI()
        {
            this.SEPET = new HashSet<SEPET>();
        }
    
        public int ID { get; set; }
        public string ADISOYADI { get; set; }
        public string TCKIMLIKNO { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public string SIFRE { get; set; }
        public Nullable<int> YASADIGISEHIRID { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual SEHIRLER SEHIRLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPET> SEPET { get; set; }
    }
}
