//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONELLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONELLER()
        {
            this.FIS = new HashSet<FIS>();
        }
    
        public int ID { get; set; }
        public string ADISOYADI { get; set; }
        public string TCKIMLIKNO { get; set; }
        public Nullable<int> DEPARTMANID { get; set; }
    
        public virtual DEPARTMANLAR DEPARTMANLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIS> FIS { get; set; }
    }
}
