//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPETSATIR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEPETSATIR()
        {
            this.FATURALAR = new HashSet<FATURALAR>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SEPETID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<int> URUNADET { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURALAR> FATURALAR { get; set; }
        public virtual SEPET SEPET { get; set; }
        public virtual URUNLER URUNLER { get; set; }
    }
}
