//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEPET()
        {
            this.FATURALAR = new HashSet<FATURALAR>();
            this.FIS = new HashSet<FIS>();
            this.SEPETSATIR = new HashSet<SEPETSATIR>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MUSTERIID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ADRES { get; set; }
        public Nullable<bool> KONTROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURALAR> FATURALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIS> FIS { get; set; }
        public virtual MUSTERI MUSTERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPETSATIR> SEPETSATIR { get; set; }
    }
}
