//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REEDERSTAJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNLER()
        {
            this.SEPETSATIR = new HashSet<SEPETSATIR>();
            this.FIYATDEGISTIR = new HashSet<FIYATDEGISTIR>();
        }
    
        public int ID { get; set; }
        public string ADI { get; set; }
        public Nullable<double> FIYAT { get; set; }
        public Nullable<int> STOKMIKTAR { get; set; }
        public Nullable<int> KATEGORIID { get; set; }
        public string IMG { get; set; }
        public Nullable<bool> KALDIR { get; set; }
        public string KODU { get; set; }
    
        public virtual KATEGORILER KATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPETSATIR> SEPETSATIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIYATDEGISTIR> FIYATDEGISTIR { get; set; }
    }
}
